# Generated by Django 4.2.27 on 2025-12-17 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(default='000.000.000-00', max_length=14),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='email',
            field=models.EmailField(default='email@exemplo.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='remuneracao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
